apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard
  name: dashboard
spec:
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 18080
  selector:
    app: dashboard
  type: LoadBalancer
