apiVersion: v1
kind: Service
metadata:
  labels:
    app: dashboard
  name: pl-blue-green-svc
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: dashboard
  type: LoadBalancer
